[project]
name = "polling-vs-sse-python"
version = "0.1.0"
description = "Compare polling and SSE"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
]
